# Generated by Django 5.1.6 on 2025-03-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPLease',
            fields=[
                ('mac_address', models.CharField(help_text='MAC address of the client', max_length=17, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(help_text='Assigned IP address')),
                ('hostname', models.CharField(blank=True, default='Unknown', help_text='Client hostname', max_length=255)),
                ('expiry_time', models.DateTimeField(help_text='When this lease expires')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this lease was last updated')),
            ],
            options={
                'verbose_name': 'DHCP Lease',
                'verbose_name_plural': 'DHCP Leases',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('chassis_id', models.CharField(help_text='Router chassis ID (MAC address)', max_length=50, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(help_text='Router IP address')),
                ('hostname', models.CharField(default='UnassignedRouter', help_text='Router hostname', max_length=255)),
                ('last_discovered', models.DateTimeField(auto_now=True, help_text='When this router was last discovered')),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='RouterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_chassis_id', models.CharField(help_text='Remote router chassis ID', max_length=50)),
                ('remote_system_name', models.CharField(blank=True, help_text='Remote router system name', max_length=255)),
                ('local_interface', models.CharField(help_text='Local interface name', max_length=100)),
                ('remote_interface', models.CharField(help_text='Remote interface name', max_length=100)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.router')),
            ],
            options={
                'unique_together': {('router', 'remote_chassis_id', 'local_interface')},
            },
        ),
    ]
